name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, fileinfo, openssl
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Install Node dependencies
        run: npm install --omit=dev && npm run prod

      - name: Copy environment file
        run: cp .env.example .env

      - name: Configure Application
        run: |
          php artisan cache:clear
          php artisan config:clear
          php artisan key:generate

      - name: Execute tests
        run: vendor/bin/phpunit
